version: "2"
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gocognit
    - gocritic
    - lll
    - unused
    - exhaustruct
    - ineffassign
    - misspell
    - gocyclo
    - dupl
    - revive
    - nolintlint
    - funlen
    - sloglint
    - interfacebloat
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
run:
  tests: false
formatters:
  enable:
    - goimports
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard # встроенные пакеты
        - default # внешние пакеты
        - prefix(github.com/artmexbet/avito_test_task) # внутренние пакеты