version: "2"
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gocognit
    - gocritic
    - lll
    - unused
    - exhaustruct
    - ineffassign
    - misspell
    - gocyclo
    - dupl
    - revive
    - nolintlint
    - funlen
    - sloglint
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
formatters:
  enable:
    - goimports
    - gofmt