// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package queries

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const AddUsers = `-- name: AddUsers :batchone
INSERT INTO users (id, username, team_id) VALUES
  ($1, $2, $3)
RETURNING id, username, team_id, is_active, created_at, updated_at
`

type AddUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddUsersParams struct {
	ID       string
	Username string
	TeamID   string
}

func (q *Queries) AddUsers(ctx context.Context, arg []AddUsersParams) *AddUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Username,
			a.TeamID,
		}
		batch.Queue(AddUsers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddUsersBatchResults{br, len(arg), false}
}

func (b *AddUsersBatchResults) QueryRow(f func(int, User, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i User
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *AddUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
