// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"
)

type PullRequest struct {
	ID        string
	Name      string
	AuthorID  string
	CreatedAt time.Time
	MergedAt  time.Time
}

type PullRequestsReviewer struct {
	PullRequestID string
	ReviewerID    string
	AssignedAt    time.Time
}

type Team struct {
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        string
	Username  string
	TeamName  string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
