// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_requests.sql

package queries

import (
	"context"
)

const CreatePullRequest = `-- name: CreatePullRequest :one
INSERT INTO pull_requests (id, name, author_id)
VALUES ($1, $2, $3)
RETURNING id, name, author_id, created_at, merged_at
`

type CreatePullRequestParams struct {
	ID       string
	Name     string
	AuthorID string
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, CreatePullRequest, arg.ID, arg.Name, arg.AuthorID)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthorID,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const GetPullRequestByID = `-- name: GetPullRequestByID :one
SELECT id, name, author_id, created_at, merged_at
FROM pull_requests
WHERE id = $1
`

func (q *Queries) GetPullRequestByID(ctx context.Context, id string) (PullRequest, error) {
	row := q.db.QueryRow(ctx, GetPullRequestByID, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthorID,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const MergePullRequest = `-- name: MergePullRequest :one
UPDATE pull_requests
SET merged_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, author_id, created_at, merged_at
`

func (q *Queries) MergePullRequest(ctx context.Context, id string) (PullRequest, error) {
	row := q.db.QueryRow(ctx, MergePullRequest, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthorID,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}
