// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviewing.sql

package queries

import (
	"context"
)

const getReviewersByPullRequestID = `-- name: GetReviewersByPullRequestID :many
SELECT u.id, u.username, u.team_name, u.is_active, u.created_at, u.updated_at
FROM pull_requests_reviewers prr
         JOIN users u ON u.id = prr.reviewer_id
WHERE prr.pull_request_id = $1
`

func (q *Queries) GetReviewersByPullRequestID(ctx context.Context, pullRequestID string) ([]User, error) {
	rows, err := q.db.Query(ctx, getReviewersByPullRequestID, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TeamName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersReviewingPullRequest = `-- name: GetUsersReviewingPullRequest :many
SELECT pr.id, pr.name, pr.author_id, pr.created_at, pr.merged_at
FROM pull_requests_reviewers prr
         JOIN pull_requests pr ON pr.id = prr.pull_request_id AND pr.merged_at IS NULL
WHERE prr.reviewer_id = $1
`

func (q *Queries) GetUsersReviewingPullRequest(ctx context.Context, reviewerID string) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, getUsersReviewingPullRequest, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AuthorID,
			&i.CreatedAt,
			&i.MergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserReviewerForPullRequest = `-- name: IsUserReviewerForPullRequest :one
SELECT EXISTS (SELECT 1
               FROM pull_requests_reviewers
               WHERE pull_request_id = $1
                 AND reviewer_id = $2) AS "exists"
`

type IsUserReviewerForPullRequestParams struct {
	PullRequestID string
	ReviewerID    string
}

func (q *Queries) IsUserReviewerForPullRequest(ctx context.Context, arg IsUserReviewerForPullRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserReviewerForPullRequest, arg.PullRequestID, arg.ReviewerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reassignReviewerForPullRequest = `-- name: ReassignReviewerForPullRequest :exec
UPDATE pull_requests_reviewers
SET reviewer_id = $2
WHERE pull_request_id = $1
  AND reviewer_id = $3
`

type ReassignReviewerForPullRequestParams struct {
	PullRequestID string
	ReviewerID    string
	ReviewerID_2  string
}

func (q *Queries) ReassignReviewerForPullRequest(ctx context.Context, arg ReassignReviewerForPullRequestParams) error {
	_, err := q.db.Exec(ctx, reassignReviewerForPullRequest, arg.PullRequestID, arg.ReviewerID, arg.ReviewerID_2)
	return err
}
