// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package queries

import (
	"context"
)

const getAssignmentStats = `-- name: GetAssignmentStats :many
SELECT prr.reviewer_id,
       u.is_active,
       COUNT(prr.pull_request_id) AS assigned_pull_requests
FROM pull_requests_reviewers prr
         JOIN users u ON prr.reviewer_id = u.id
GROUP BY prr.reviewer_id, u.id
ORDER BY assigned_pull_requests
`

type GetAssignmentStatsRow struct {
	ReviewerID           string
	IsActive             bool
	AssignedPullRequests int64
}

func (q *Queries) GetAssignmentStats(ctx context.Context) ([]GetAssignmentStatsRow, error) {
	rows, err := q.db.Query(ctx, getAssignmentStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignmentStatsRow
	for rows.Next() {
		var i GetAssignmentStatsRow
		if err := rows.Scan(&i.ReviewerID, &i.IsActive, &i.AssignedPullRequests); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsCount = `-- name: GetTeamsCount :many
SELECT t.name, COUNT(*) AS pr_count
FROM pull_requests_reviewers prr
         JOIN users u ON u.id = prr.reviewer_id
         JOIN teams t ON u.team_name = t.name
GROUP BY t.name
`

type GetTeamsCountRow struct {
	Name    string
	PrCount int64
}

func (q *Queries) GetTeamsCount(ctx context.Context) ([]GetTeamsCountRow, error) {
	rows, err := q.db.Query(ctx, getTeamsCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamsCountRow
	for rows.Next() {
		var i GetTeamsCountRow
		if err := rows.Scan(&i.Name, &i.PrCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersCount = `-- name: GetUsersCount :many
SELECT u.is_active, COUNT(*) AS user_count
FROM users u
GROUP BY u.is_active
`

type GetUsersCountRow struct {
	IsActive  bool
	UserCount int64
}

func (q *Queries) GetUsersCount(ctx context.Context) ([]GetUsersCountRow, error) {
	rows, err := q.db.Query(ctx, getUsersCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersCountRow
	for rows.Next() {
		var i GetUsersCountRow
		if err := rows.Scan(&i.IsActive, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
