// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package queries

import (
	"context"
)

const AddTeam = `-- name: AddTeam :one
INSERT INTO teams (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name       = EXCLUDED.name,
                                 updated_at = CURRENT_TIMESTAMP
RETURNING name, created_at, updated_at
`

func (q *Queries) AddTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, AddTeam, name)
	var i Team
	err := row.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const GetTeamByName = `-- name: GetTeamByName :one
SELECT name, created_at, updated_at
FROM teams
WHERE name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, GetTeamByName, name)
	var i Team
	err := row.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
