// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"
)

const existsUserByID = `-- name: ExistsUserByID :one
SELECT EXISTS (SELECT 1
               FROM users
               WHERE id = $1) AS "exists"
`

func (q *Queries) ExistsUserByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActiveUsersByTeamName = `-- name: GetActiveUsersByTeamName :many
SELECT id, username, team_name, is_active, created_at, updated_at
FROM users
WHERE team_name = $1
  AND is_active = TRUE
`

func (q *Queries) GetActiveUsersByTeamName(ctx context.Context, teamName string) ([]User, error) {
	rows, err := q.db.Query(ctx, getActiveUsersByTeamName, teamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TeamName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, team_name, is_active, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByTeamName = `-- name: GetUsersByTeamName :many
SELECT id, username, team_name, is_active, created_at, updated_at
FROM users
WHERE team_name = $1
`

func (q *Queries) GetUsersByTeamName(ctx context.Context, teamName string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByTeamName, teamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TeamName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserIsActiveByID = `-- name: SetUserIsActiveByID :one
UPDATE users
SET is_active  = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, team_name, is_active, created_at, updated_at
`

type SetUserIsActiveByIDParams struct {
	ID       string
	IsActive bool
}

func (q *Queries) SetUserIsActiveByID(ctx context.Context, arg SetUserIsActiveByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserIsActiveByID, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
